name: car_reservation_app
description: A Flutter multiplatform car reservation app with clean architecture and high security.

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  dio: ^5.0.0
  flutter_secure_storage: ^8.0.0
  flutter_screenutil: ^5.5.3+2
  websocket: ^2.0.1
  # Add other dependencies as needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
